compile: object
	gcc -o amedanha main.o funcoes_entrada.o funcoes_output.o funcoes_pontuacao.o funcoes_tempo.o funcoes_sorteio.o funcoes_alocacao.o play.o

object:
	gcc -c main.c funcoes_entrada.c funcoes_output.c funcoes_pontuacao.c funcoes_tempo.c funcoes_sorteio.c funcoes_alocacao.c play.c
